name: Deploy Release


on:
  # Trigger the workflow on push action in develop branch
  # So it will trigger when the PR of the feature branch was merged.
  push:
    branches:
      - main
jobs:
  app_deploy:
    name: Deploy and upload to JitPack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Read version.properties
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./local.properties
        
      - uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: 'feat=branch-name'
          split-by: '='

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: "308"
          release_name: "Release ${{ steps.split.outputs._1}}"
          draft: false
          prerelease: false
