name: Deploy Release


on:
  # Trigger the workflow on push action in develop branch
  # So it will trigger when the PR of the feature branch was merged.
  push:
    branches:
      - main
jobs:
  app_deploy:
    name: Deploy and upload to JitPack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Read branch.properties
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./local.properties
        
        

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: "300"
          release_name: ${{ steps.version.outputs.content }}
          draft: false
          prerelease: false
