name: Deploy Release


on:
  # Trigger the workflow on push action in develop branch
  # So it will trigger when the PR of the feature branch was merged.
  push:
    branches:
      - main
jobs:
  app_deploy:
    name: Deploy and upload to JitPack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Access APOD_API_KEY
        env:
          APOD_API_KEY: ${{ secrets.APOD_API_KEY }}
        run: echo APOD_API_KEY=\"$APOD_API_KEY\" > ./local.properties

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: '204'
          release_name: ${{APOD_API_KEY }}
          draft: false
          prerelease: false
